### ISSUE TITLE
Login no longer works

### ISSUE THREAD

**Issue by JeppeTh** [fuzeman/spotify.py#4]
Seems a fix exists...
https://github.com/makap/spotify.py/commit/e047e236f30fd68b6376a753171fe1615ea482e0#diff-9aeab829e27266990f352631530f9f8d

**Comment by fuzeman** [comment]
Fixed in v0.8.4

**Comment by amuaamua** [comment]
Hi, coming from @TooTallNate's Node-spotify-web, I have tested your library with a premium user, but it doesn't work :( It hangs the communication just after the login call.

Here's the debugging:

```
DEBUG:pyemitter:[spotify.core.request.Request      ]:emit(event: 'success', args: ({u'id': 5, u'result': {u'head_files': u'0', u'lastfm_session': u'', u'product': u'premium', u'publish_activity': u'0', u'post_open_graph': u'0', u'ads': u'0', u'publish_playlist': u'1', u'app_developer': u'0', u'country': u'ES', u'license_agreements': u'0.8.8-ES', u'head_files_url': u'http://heads-ak.spotify.com.edgesuite.net/head/{file_id}', u'ab_test_group': u'926', u'catalogue': u'premium', u'user': u'**********', u'wanted_licenses': u'0.8.8-ES', u'preferred_locale': u'es-es', u'link_tutorial_completed': u'1', u'public_toplist': u'7', u'ab_collection_union': u'1'}},), kwargs: {})
DEBUG:pyemitter:[spotify.client.Spotify            ]:emit(event: 'login', args: (), kwargs: {})
DEBUG:pyemitter:[spotify.core.request.Request      ]:pipe(events: ['error'], other: <spotify.components.connection.Connection object at 0x10e909290>)
```

**Comment by fuzeman** [comment]
@amuaamua what does your python code look like? the "login" event means the client has finished connecting to Spotify and is ready for commands.

**Note:** the `emit(event: 'login', args: (), kwargs: {})` message means the event was emitted on the `Spotify` object, it doesn't mean a "login" message was sent to spotify.

**Comment by amuaamua** [comment]
Hi, I'm using your example code, with the artist.py file. It gets stuck on login.

**Comment by amuaamua** [comment]
U're right, sorry. But the websocket communication stops right before asking the track urls. did you implement that part of the communication?

Thx!

**Comment by fuzeman** [comment]
That's strange, the "artist.py" example is still working for me.. not sure why it would stop after the "login" event for you.

---

Any chance you could provide a full log file?

Censor/Remove any lines containing the following strings to ensure any personal details aren't included:
- `Landing - CSRF token`
-  `"name":"connect","id":"0"}`
- `{u'head_files': u'0'`

**Comment by amuaamua** [comment]
Mmm, some changes made and it now works. I don't exactly know what happens.

Anyway, thanks for your code and your time ;)
